### ISSUE TITLE
template question

### ISSUE THREAD

**Issue by boneskull** [miguelmota/jsdoc-oblivion#1]
If I want to use these templates, but override the default `layout` template (specifically, I wish to inject a couple `<script>` tags into it), what's the easiest way to do that?  Having trouble figuring this out from the JSDoc docs.

Thanks!

**Comment by miguelmota** [comment]
One way is to insert script tag(s) in config template footer option

`conf.json`

```json
{
  "templates": {
    "footer": "<script src=\"https://example.com/script.js\"></script>"
  }
}
```

**Comment by miguelmota** [comment]
From docs http://usejsdoc.org/about-configuring-default-template.html#overriding-the-default-template-s-layout-file

> **Overriding the default template's layout file**
> 
> The default template uses a file named **layout.tmpl** to specify the header and footer for each page in the generated documentation. In particular, this file defines which CSS and JavaScript files are loaded for each page. In JSDoc 3.3.0 and later, you can specify your own **layout.tmpl** file to use, which allows you to load your own custom CSS and JavaScript files in addition to, or instead of, the standard files.
> 
> To use this feature, set the option **`templates.default.layoutFile`** to the path to your customized layout file. Relative paths are resolved against the current working directory; the path to the configuration file; and the JSDoc directory, in that order.
