### ISSUE TITLE
several security issues detected by retire.js

### ISSUE THREAD

**Issue by KaiSchwarz-cnic** [miguelmota/jsdoc-oblivion#4]
retire.js check brought the following to me:

node_modules/jsdoc-oblivion/template/moment.js
 ↳ moment.js 2.6.0 has known vulnerabilities: severity: low; summary: reDOS - regular expression denial of service; https://github.com/moment/moment/issues/2936

node_modules/jsdoc-oblivion/docs/scripts/prettify/jquery.min.js
 ↳ jquery 2.0.0 has known vulnerabilities: severity: medium; issue: 2432, summary: 3rd party CORS request may execute; https://github.com/jquery/jquery/issues/2432 http://blog.jquery.com/2016/01/08/jquery-2-2-and-1-12-released/

node_modules/jsdoc-oblivion/template/static/scripts/prettify/jquery.min.js
 ↳ jquery 2.0.0 has known vulnerabilities: severity: medium; issue: 2432, summary: 3rd party CORS request may execute; https://github.com/jquery/jquery/issues/2432 http://blog.jquery.com/2016/01/08/jquery-2-2-and-1-12-released/

so, please be so kind to upgrade this dependency.

Thanks!

**Comment by miguelmota** [comment]
@papakai thanks for reporting!

**Comment by KaiSchwarz-cnic** [comment]
@miguelmota you're welcome, thanks for fixing it
